[project]
name = "llm-ui"
version = "0.1.0"
description = "Utility for interacting with ollama-managed LLMs"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "ollama>=0.4.7",
    "termcolor>=2.5.0",
    "types-colorama>=0.4.15.20240311",
]
