[project]
name = "llm-cli"
version = "0.1.0"
description = "Utility scripts for interacting with ollama-managed LLMs via CLI"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ollama>=0.4.7",
]
